[INFO              ] Logger: Record log in /home/nanoproc/ilislife/logs/kivy_16-07-21_27.txt
[INFO              ] Factory: 179 symbols loaded
[DEBUG             ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG             ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[DEBUG             ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG             ] Cache: register <kv.shader> with limit=1000, timeout=3600
[DEBUG             ] Cache: register <kv.lang> with limit=None, timeout=None
[DEBUG             ] Window: Ignored <egl_rpi> (import error)
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] Window: Provider: sdl2(['window_egl_rpi'] ignored)
[INFO              ] GL: OpenGL version <b'3.0 Mesa 11.2.0'>
[INFO              ] GL: OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO              ] GL: OpenGL renderer <b'Mesa DRI Intel(R) Ivybridge Mobile '>
[INFO              ] GL: OpenGL parsed version: 3, 0
[INFO              ] GL: Shading version <b'1.30'>
[INFO              ] GL: Texture max size <8192>
[INFO              ] GL: Texture max units <16>
[DEBUG             ] Shader: Fragment compiled successfully
[DEBUG             ] Shader: Vertex compiled successfully
[DEBUG             ] ImageSDL2: Load </usr/lib/python3/dist-packages/kivy/data/glsl/default.png>
[INFO              ] Window: auto add sdl2 input provider
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] Text: Provider: sdl2
[DEBUG             ] Cache: register <textinput.label> with limit=None, timeout=60.0
[DEBUG             ] Cache: register <textinput.width> with limit=None, timeout=60.0
[DEBUG             ] App: Loading kv <./ilislife.kv>
[DEBUG             ] Resource: add </usr/share/fonts/truetype> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/lohit-punjabi> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/freefont> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/ubuntu-font-family> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/kacst-one> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/kacst> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/padauk> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/ancient-scripts> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/fonts-guru-extra> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/takao-mincho> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/takao-gothic> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/lao> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/tibetan-machine> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/dejavu> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/ttf-khmeros-core> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/liberation> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/sinhala> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/tlwg> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/openoffice> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/nanum> in path list
[DEBUG             ] Resource: add </usr/share/fonts/truetype/abyssinica> in path list
[DEBUG             ] Resource: add </usr/local/share/fonts> in path list
[DEBUG             ] Resource: add </usr/lib/python3/dist-packages/kivy/data/fonts> in path list
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1742, in create_handler
[WARNING           ] stderr:     return eval(value, idmap), bound_list
[WARNING           ] stderr:   File "./ilislife.kv", line 38, in <module>
[WARNING           ] stderr:     text: str(root.seq_now)+'[sub]th[/sub]   '+str(root.seq[root.seq_now][0])+'[sub]V[/sub]  '+str(root.seq[root.seq_now][1]+'[sub]s[/sub]')
[WARNING           ] stderr: TypeError: unsupported operand type(s) for +: 'int' and 'str'
[WARNING           ] stderr: 
[WARNING           ] stderr: During handling of the above exception, another exception occurred:
[WARNING           ] stderr: 
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2115, in _apply_rule
[WARNING           ] stderr:     rctx['ids'])
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1747, in create_handler
[WARNING           ] stderr:     cause=tb)
[WARNING           ] stderr: kivy.lang.BuilderException: Parser: File "./ilislife.kv", line 38:
[WARNING           ] stderr: ...
[WARNING           ] stderr:      36:                    markup: True
[WARNING           ] stderr:      37:                Label:
[WARNING           ] stderr: >>   38:                    text: str(root.seq_now)+'[sub]th[/sub]   '+str(root.seq[root.seq_now][0])+'[sub]V[/sub]  '+str(root.seq[root.seq_now][1]+'[sub]s[/sub]')
[WARNING           ] stderr:      39:                    # size_hint_y: 0.2
[WARNING           ] stderr:      40:                    markup: True
[WARNING           ] stderr: ...
[WARNING           ] stderr: TypeError: unsupported operand type(s) for +: 'int' and 'str'
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1742, in create_handler
[WARNING           ] stderr:     return eval(value, idmap), bound_list
[WARNING           ] stderr:   File "./ilislife.kv", line 38, in <module>
[WARNING           ] stderr:     text: str(root.seq_now)+'[sub]th[/sub]   '+str(root.seq[root.seq_now][0])+'[sub]V[/sub]  '+str(root.seq[root.seq_now][1]+'[sub]s[/sub]')
[WARNING           ] stderr: 
[WARNING           ] stderr: 
[WARNING           ] stderr: During handling of the above exception, another exception occurred:
[WARNING           ] stderr: 
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "main.py", line 582, in <module>
[WARNING           ] stderr:     IlislifeApp().run()
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/app.py", line 801, in run
[WARNING           ] stderr:     self.load_kv(filename=self.kv_file)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/app.py", line 598, in load_kv
[WARNING           ] stderr:     root = Builder.load_file(rfilename)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1842, in load_file
[WARNING           ] stderr:     return self.load_string(data, **kwargs)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1920, in load_string
[WARNING           ] stderr:     widget = Factory.get(parser.root.name)()
[WARNING           ] stderr:   File "main.py", line 94, in __init__
[WARNING           ] stderr:     super().__init__(**kwargs)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/uix/boxlayout.py", line 102, in __init__
[WARNING           ] stderr:     super(BoxLayout, self).__init__(**kwargs)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/uix/layout.py", line 72, in __init__
[WARNING           ] stderr:     super(Layout, self).__init__(**kwargs)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/uix/widget.py", line 320, in __init__
[WARNING           ] stderr:     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1970, in apply
[WARNING           ] stderr:     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2130, in _apply_rule
[WARNING           ] stderr:     e), cause=tb)
[WARNING           ] stderr: kivy.lang.BuilderException: Parser: File "./ilislife.kv", line 38:
[WARNING           ] stderr: ...
[WARNING           ] stderr:      36:                    markup: True
[WARNING           ] stderr:      37:                Label:
[WARNING           ] stderr: >>   38:                    text: str(root.seq_now)+'[sub]th[/sub]   '+str(root.seq[root.seq_now][0])+'[sub]V[/sub]  '+str(root.seq[root.seq_now][1]+'[sub]s[/sub]')
[WARNING           ] stderr:      39:                    # size_hint_y: 0.2
[WARNING           ] stderr:      40:                    markup: True
[WARNING           ] stderr: ...
[WARNING           ] stderr: BuilderException: Parser: File "./ilislife.kv", line 38:
[WARNING           ] stderr: ...
[WARNING           ] stderr:      36:                    markup: True
[WARNING           ] stderr:      37:                Label:
[WARNING           ] stderr: >>   38:                    text: str(root.seq_now)+'[sub]th[/sub]   '+str(root.seq[root.seq_now][0])+'[sub]V[/sub]  '+str(root.seq[root.seq_now][1]+'[sub]s[/sub]')
[WARNING           ] stderr:      39:                    # size_hint_y: 0.2
[WARNING           ] stderr:      40:                    markup: True
[WARNING           ] stderr: ...
[WARNING           ] stderr: TypeError: unsupported operand type(s) for +: 'int' and 'str'
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1742, in create_handler
[WARNING           ] stderr:     return eval(value, idmap), bound_list
[WARNING           ] stderr:   File "./ilislife.kv", line 38, in <module>
[WARNING           ] stderr:     text: str(root.seq_now)+'[sub]th[/sub]   '+str(root.seq[root.seq_now][0])+'[sub]V[/sub]  '+str(root.seq[root.seq_now][1]+'[sub]s[/sub]')
[WARNING           ] stderr: 
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2115, in _apply_rule
[WARNING           ] stderr:     rctx['ids'])
[WARNING           ] stderr:   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1747, in create_handler
[WARNING           ] stderr:     cause=tb)
[WARNING           ] stderr: 
